apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
 DB_HOST: mysql
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  # these labels belongs to replicaset resource
  namespace: expense
  labels:
    tier: app
    component: backend
    project: expense
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      tier: app
      component: backend
      project: expense
  # below is pod definition    
  template:
    metadata:
    # these labels belongs to pod
      labels:
        tier: app
        component: backend
        project: expense
    spec:
      initContainers:
      - name: init-myservice
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup mysql; do echo waiting for myservice; sleep 2; done"]
      containers:  
      - name: nginx
        image: iamraja/backend:v1.0
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "150m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 2
          periodSeconds: 5
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 2
          periodSeconds: 5
          initialDelaySeconds: 30
        envFrom:
        - configMapRef:
           name: backend


---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
        tier: app
        component: backend
        project: expense
  ports:
  - protocol: TCP
    port: 8080 #service-port
    targetPort: 8080 #targetport

